name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo -i && sudo apt-get update -y && apt remove curl && apt purge curl && apt-get install -y libssl-dev autoconf libtool make wget && cd /usr/local/src &&
rm -rf curl* && wget https://curl.haxx.se/download/curl-7.70.0.zip && unzip curl-7.70.0.zip && cd curl-7.70.0 && ./buildconf && ./configure --with-ssl && make && make install && mv /usr/bin/curl /usr/bin/curl.bak && cp /usr/local/bin/curl /usr/bin/curl && curl -V 
      - run: curl -V
      # Install git ftp and make it executable
      - run: mkdir ~/bin && curl https://raw.githubusercontent.com/git-ftp/git-ftp/master/git-ftp > ~/bin/git-ftp
      - run: chmod +x ~/bin/git-ftp
      - run: git clone https://github.com/jakshaygalaxy2020/gittest2020.git 
      - run: cd gittest2020 && pwd && ls -la .git/ && git status && git fetch && git init

      - run: git config --global user.email "akshay.jain@galaxyweblinks.in"
      - run: git config --global user.name "jakshaygalaxy2020"
      # Use git-ftp to copy all the files to the server, while keeping the connection
      - run: git ftp push -vv --user upload --passwd "Galaxy@123" "sftp://54.196.210.220:22/home/upload/"
