name: learn-github-actions
on:
  workflow_dispatch: 
    branches:
    - development
jobs:
  check-bats-version:
#    if: contains( github.ref, 'development')
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: apt-get update -y && test -d ~/.ssh || mkdir ~/.ssh && chmod 700 ~/.ssh && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config && chmod 600 ~/.ssh/config
      - run: mkdir ~/bin && curl https://raw.githubusercontent.com/git-ftp/git-ftp/master/git-ftp > ~/bin/git-ftp
      - run: chmod +x ~/bin/git-ftp
      - run: git config --global user.email "akshay.jain@galaxyweblinks.in"
      - run: git config --global user.name "jakshaygalaxy2020"
      # Use git-ftp to copy all the files to the server, while keeping the connection
      - run: echo ${{ secrets.USER }} && echo ${{ secrets.PASS }}
#      - shell: bash
#        env:
#          SUPER_SECRET: ${{ secrets.SuperSecret }} ${{ secrets.USER }} ${{ secrets.PASS }} 
      - run: echo  ${{ secrets.PASS }}
      - run: git ftp push --user ${{ secrets.USER }} --passwd ${{ secrets.PASS }} "sftp://54.161.70.224:22/home/upload/" -f
 
